# Generated by Django 3.2.9 on 2022-01-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20211227_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_completed',
            field=models.BooleanField(default=False),
        ),
    ]
